PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX rr: <http://www.w3.org/ns/r2rml#>.
PREFIX rml: <http://semweb.mmlab.be/ns/rml#>.
PREFIX ql: <http://semweb.mmlab.be/ns/ql#>.
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>.
PREFIX ns: <http://accidentestrafico.org/traffic/ontology/TrafficOntology#>.
PREFIX owl: <http://www.w3.org/2002/07/owl#> .
PREFIX : <http://accidentestrafico.org/traffic/resource/>.


# Obtener la ubicación de cada accidente con coordenadas
SELECT ?accidente ?coordenadas
WHERE {
  ?accidente ns:OcurreEn ?direccion .
  ?direccion ns:coordenadas ?coordenadas .
}

# Filtrar accidentes donde el estado meteorológico sea "Despejado"
SELECT ?accidente ?fecha
WHERE {
  ?accidente ns:TieneEstadoMeteorologico ?estadoMeteorologico ;
             ns:fecha ?fecha .
  ?estadoMeteorologico ns:estadoMeteorologico "Despejado" .
}

# Obtener los accidentes con pasajeros como tipo de persona
SELECT ?accidente ?tipoPersona
WHERE {
  ?accidente ns:ParticipaPersona ?persona .
  ?persona ns:tipoDePersona "Pasajero" .
}

# Contar el número total de accidentes
SELECT (COUNT(?accidente) AS ?totalAccidentes)
WHERE {
  ?accidente a ns:Accidente ;
             ns:fecha ?fecha .
}

#Accidentes con Motocicletas implicadas
SELECT ?accidente ?tipoVehiculo
WHERE {
  ?accidente ns:OcurreEn ?direccion ;
             ns:InvolucraVehiculo ?vehiculo .
  ?vehiculo ns:tipoVehiculo "Motocicleta" .  # Filtrar por motocicleta
}


# Listar los accidentes donde hubo prueba positiva de alcohol
SELECT ?accidente ?fecha
WHERE {
  ?accidente ns:ParticipaPersona ?persona ;
             ns:fecha ?fecha .
  ?persona ns:positivaAlcohol "YES" .
}

# Obtener accidentes y su distrito con el enlace a Wikidata
SELECT ?accidente ?distrito ?distrito_Wikidata
WHERE {
  ?accidente ns:OcurreEn ?direccion .
  ?direccion ns:distrito ?distrito .
  ?direccion ns:distrito_Wikidata ?distrito_Wikidata .
  FILTER(STRSTARTS(STR(?distrito_Wikidata), "http://www.wikidata.org/entity/Q"))
}